CREATE TABLE media (
    id UUID PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    media_type VARCHAR(16) NOT NULL,
    content BYTEA NOT NULL
);

ALTER TABLE films ADD COLUMN poster_id UUID;
ALTER TABLE films ADD CONSTRAINT fk_films_poster FOREIGN KEY (poster_id) REFERENCES media(id) ON DELETE SET NULL;